spring.application.name=urlshortener

# --- Server -------------------------------------
server.port=8080

# --- Datasource (PostgreSQL) --------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgres

# --- JPA / Hibernate ----------------------------
spring.jpa.hibernate.ddl-auto=validate

# --- Flyway -------------------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# --- Redis --------------------------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379