# Server Configuration
server.port=8081

# Timezone Configuration
spring.jackson.time-zone=UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5434/urlshortener
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.connection-init-sql=SELECT 1

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.batch_size=10
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://127.0.0.1:5434/urlshortener
spring.flyway.user=postgres
spring.flyway.password=postgres

# Redis Configuration
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379

# Cache Configuration
spring.cache.type=redis
# 1 hour in milliseconds
spring.cache.redis.time-to-live=3600000